version: '3'
services:
  react-app:
    build:
      context: ./React
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - buildno
        - gitcommithash
        - gitcommitmessage
    container_name: mycarlong-front_react-app
    ports:
      - "3007:80"
    env_file:
      - .env
    environment:
      - REACT_APP_GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - REACT_APP_BASE_URL=${BASE_URL}
      - REACT_APP_GPT_API_KEY=${GPT_API_KEY}
      - REACT_APP_NAME_SECRET_KEY=${NAME_SECRET_KEY}
      - REACT_APP_GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    depends_on:
      - express-app
    networks:
      - mycarlong_network

  express-app:
    build:
      context: ./Express
      dockerfile: Dockerfile
    container_name: mycarlong-front_express-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - BASE_URL=${BASE_URL}
      - GPT_API_KEY=${GPT_API_KEY}
      - NAME_SECRET_KEY=${NAME_SECRET_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    networks:
      - mycarlong_network

networks:
  mycarlong_network:
    driver: bridge