name: Deploy

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

      - name: Install dependencies for both React and Express
        run: |
          cd React && npm install
          cd ../Express && npm install

      - name: Adjust Swappiness
        run: |
          sudo sysctl vm.swappiness=80

      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.EC2_IAM_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.EC2_IAM_SECRET_KEY }}
          aws-region: ${{ secrets.EC2_REGION }}

      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.EC2_SE_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.EC2_IAM_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.EC2_IAM_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.EC2_REGION }}

      - name: Get the commit message
        id: commit
        run: echo "::set-output name=message::$(git log --format=%B -n 1)"
      - name: Create .env file
        run: |
          echo "REACT_APP_GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env
          echo "REACT_APP_BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "REACT_APP_GPT_API_KEY=${{ secrets.GPT_API_KEY }}" >> .env
          echo "REACT_APP_NAME_SECRET_KEY=${{ secrets.NAME_SECRET_KEY }}" >> .env
          echo "REACT_APP_GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> .env
          echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "GPT_API_KEY=${{ secrets.GPT_API_KEY }}" >> .env
          echo "NAME_SECRET_KEY=${{ secrets.NAME_SECRET_KEY }}" >> .env
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> .env

      - name: Build the React application
        env:
          NODE_OPTIONS: --max_old_space_size=4096  # 메모리 할당 한도를 4GB로 설정
          GENERATE_SOURCEMAP: false  # 소스 맵 생성을 비활성화
          CI: false  # CI 환경 변수를 false로 설정
        run: |
          cd React
          echo "Memory usage before build:"
          free -m
          CI=false npm run build  # npm run build 명령어 실행
          echo "Memory usage after build:"
          free -m

      - name: Deploy to EC2
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
          NAME_SECRET_KEY: ${{ secrets.NAME_SECRET_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          scp -o StrictHostKeyChecking=no -i /tmp/ssh_key .env ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/root/.env
          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            if [ -d "/home/ubuntu/MyCarLong-Front" ]; then
              rm -rf /home/ubuntu/MyCarLong-Front
            fi
            git clone --branch release https://github.com/MyCarLong/MyCarLong-Front.git /home/ubuntu/MyCarLong-Front
            cp /root/.env /home/ubuntu/MyCarLong-Front/.env
            cd /home/ubuntu/MyCarLong-Front
            docker-compose down
            docker-compose build --no-cache  --build-arg buildno=${{ github.run_number }} --build-arg gitcommithash=${{ github.sha }} --build-arg gitcommitmessage="${{ steps.commit.outputs.message }}"
            docker-compose up -d
            echo "Deployment complete."
          EOF

      - name: Remove Github Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.EC2_SE_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.EC2_IAM_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.EC2_IAM_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.EC2_REGION }}

      - name: Cleanup on success
        if: success()
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Removing .env file..."
            rm -f /home/ubuntu/MyCarLong-Front/.env
            echo "Cleanup complete."
          EOF
          rm -f /tmp/ssh_key

      - name: Cleanup on failure
        if: failure()
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Cleaning up due to build failure..."
            sudo docker stop $(sudo docker ps -q) || true
            sudo docker rm $(sudo docker ps -aq) || true
            sudo docker system prune -a -f --volumes
            sudo rm -rf /home/ubuntu/.cache/*
            sudo bash -c '
              snap list --all | awk '/disabled/{print \$1, \$3}' | while read snapname revision; do
                echo "Removing \$snapname revision \$revision"
                snap remove "\$snapname" --revision="\$revision"
              done
            '
            echo "Cleanup complete."
          EOF
          rm -f /tmp/ssh_key
